"""pub-lit add sort

Revision ID: 149f1211d8cf
Revises: 5ce68f5ee1e4
Create Date: 2025-09-24 05:08:05.065052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149f1211d8cf'
down_revision: Union[str, Sequence[str], None] = '5ce68f5ee1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_literature', sa.Column('sort', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_literature', 'sort')
    # ### end Alembic commands ###
