"""sp-add-fields

Revision ID: 1f3ae6dc065c
Revises: 149f1211d8cf
Create Date: 2025-09-24 18:42:20.061787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3ae6dc065c'
down_revision: Union[str, Sequence[str], None] = '149f1211d8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_specimen', sa.Column('recordered_by', sa.String(length=500), nullable=True))
    op.add_column('item_specimen', sa.Column('record_number', sa.String(length=500), nullable=True))
    op.add_column('item_specimen', sa.Column('catalog_number', sa.String(length=500), nullable=True))
    op.add_column('item_specimen', sa.Column('locality', sa.String(length=500), nullable=True))
    op.add_column('item_specimen', sa.Column('county', sa.String(length=500), nullable=True))
    op.add_column('item_specimen', sa.Column('institution_code', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_specimen', 'institution_code')
    op.drop_column('item_specimen', 'county')
    op.drop_column('item_specimen', 'locality')
    op.drop_column('item_specimen', 'catalog_number')
    op.drop_column('item_specimen', 'record_number')
    op.drop_column('item_specimen', 'recordered_by')
    # ### end Alembic commands ###
