"""notification-opt-content

Revision ID: 2f712036ae3d
Revises: 97434e52e385
Create Date: 2025-08-09 03:23:02.750624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f712036ae3d'
down_revision: Union[str, Sequence[str], None] = '97434e52e385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
