"""itemspecimen-sort

Revision ID: 32a10a534721
Revises: a74972763b8c
Create Date: 2025-09-30 01:51:25.098061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a10a534721'
down_revision: Union[str, Sequence[str], None] = 'a74972763b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_specimen', sa.Column('sort', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_specimen', 'sort')
    # ### end Alembic commands ###
