"""sp-field-record

Revision ID: 3ebc7820a4ce
Revises: 1f3ae6dc065c
Create Date: 2025-09-24 18:49:42.271987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebc7820a4ce'
down_revision: Union[str, Sequence[str], None] = '1f3ae6dc065c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_specimen', sa.Column('recorded_by', sa.String(length=500), nullable=True))
    op.drop_column('item_specimen', 'recordered_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_specimen', sa.Column('recordered_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('item_specimen', 'recorded_by')
    # ### end Alembic commands ###
