"""collection-pub-id

Revision ID: 4c0d8feddc89
Revises: c0e1f6fa177e
Create Date: 2025-08-29 18:31:04.691525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0d8feddc89'
down_revision: Union[str, Sequence[str], None] = 'c0e1f6fa177e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('publication_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'collection', 'publication', ['publication_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'publication_id')
    # ### end Alembic commands ###
