"""source_mixin-key

Revision ID: 52c4b6287a64
Revises: a69660e434c4
Create Date: 2025-09-01 08:10:45.778713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c4b6287a64'
down_revision: Union[str, Sequence[str], None] = 'a69660e434c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('key', sa.String(length=1000), nullable=False))
    op.add_column('item', sa.Column('key', sa.String(length=1000), nullable=False))
    op.add_column('item_specimen', sa.Column('key', sa.String(length=1000), nullable=False))
    op.alter_column('item_specimen', 'text',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('item_specimen', 'named_area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('publication_literature', sa.Column('key', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_literature', 'key')
    op.alter_column('item_specimen', 'named_area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('item_specimen', 'text',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('item_specimen', 'key')
    op.drop_column('item', 'key')
    op.drop_column('collection', 'key')
    # ### end Alembic commands ###
