"""collection-uid

Revision ID: 5b7247027367
Revises: 2f712036ae3d
Create Date: 2025-08-09 09:21:39.589420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7247027367'
down_revision: Union[str, Sequence[str], None] = '2f712036ae3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'collection', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'user_id')
    # ### end Alembic commands ###
