"""item-specimen-data

Revision ID: 5ce68f5ee1e4
Revises: fbed43a939a7
Create Date: 2025-09-19 10:53:59.085339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ce68f5ee1e4'
down_revision: Union[str, Sequence[str], None] = 'fbed43a939a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('fetched_specimen_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'fetched_specimen_data')
    # ### end Alembic commands ###
