"""item-note

Revision ID: 69aff9b6624a
Revises: ec31932a780a
Create Date: 2025-08-29 19:44:52.776472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69aff9b6624a'
down_revision: Union[str, Sequence[str], None] = 'ec31932a780a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('distribution', sa.Text(), nullable=False))
    op.add_column('item', sa.Column('note', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'note')
    op.drop_column('item', 'distribution')
    # ### end Alembic commands ###
