"""item-optional

Revision ID: a69660e434c4
Revises: 69aff9b6624a
Create Date: 2025-08-29 19:50:58.608102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69660e434c4'
down_revision: Union[str, Sequence[str], None] = '69aff9b6624a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'common_names',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('item', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('item', 'distribution',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('item', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('item', 'distribution',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('item', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('item', 'common_names',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
