"""item-specimen-history

Revision ID: a6a83b75c25a
Revises: 32a10a534721
Create Date: 2025-10-01 08:44:12.994543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6a83b75c25a'
down_revision: Union[str, Sequence[str], None] = '32a10a534721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_specimen', sa.Column('changed_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_specimen', 'changed_history')
    # ### end Alembic commands ###
