"""item-sort

Revision ID: a74972763b8c
Revises: 3ebc7820a4ce
Create Date: 2025-09-25 08:50:27.278258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74972763b8c'
down_revision: Union[str, Sequence[str], None] = '3ebc7820a4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('sort', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'sort')
    # ### end Alembic commands ###
