"""webhook

Revision ID: b44b4449ec90
Revises: 49c4e9563de5
Create Date: 2025-08-09 01:17:09.266208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b44b4449ec90'
down_revision: Union[str, Sequence[str], None] = '49c4e9563de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('item_distribution', sa.Column('item_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item_distribution', 'item', ['item_id'], ['id'])
    op.add_column('item_specimen', sa.Column('item_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item_specimen', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_specimen', type_='foreignkey')
    op.drop_column('item_specimen', 'item_id')
    op.drop_constraint(None, 'item_distribution', type_='foreignkey')
    op.drop_column('item_distribution', 'item_id')
    op.drop_table('webhook_event')
    # ### end Alembic commands ###
