"""source_mixin-key-x

Revision ID: bdd2ae6e2a01
Revises: 52c4b6287a64
Create Date: 2025-09-01 08:15:49.671591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd2ae6e2a01'
down_revision: Union[str, Sequence[str], None] = '52c4b6287a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'key',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('item', 'key',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('item_specimen', 'key',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('publication_literature', 'key',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication_literature', 'key',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('item_specimen', 'key',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('item', 'key',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('collection', 'key',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
