"""pub-add-status

Revision ID: c377ab79cc5c
Revises: bdd2ae6e2a01
Create Date: 2025-09-01 08:45:29.239093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c377ab79cc5c'
down_revision: Union[str, Sequence[str], None] = 'bdd2ae6e2a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('status', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'status')
    # ### end Alembic commands ###
