"""user-auth1

Revision ID: c7815ca504f6
Revises: 560ad9dccf27
Create Date: 2025-09-09 08:21:32.685116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7815ca504f6'
down_revision: Union[str, Sequence[str], None] = '560ad9dccf27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activation_token', sa.String(length=500), nullable=False))
    op.add_column('user', sa.Column('is_activated', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('activated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activated_at')
    op.drop_column('user', 'is_activated')
    op.drop_column('user', 'activation_token')
    # ### end Alembic commands ###
