"""optional

Revision ID: ceaad382c912
Revises: 5b7247027367
Create Date: 2025-08-09 09:36:51.705746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceaad382c912'
down_revision: Union[str, Sequence[str], None] = '5b7247027367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('item', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('item_specimen', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('publication_literature', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication_literature', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('item_specimen', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('item', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('collection', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
