"""pub-id-not-null

Revision ID: ec31932a780a
Revises: 4c0d8feddc89
Create Date: 2025-08-29 18:39:22.380081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec31932a780a'
down_revision: Union[str, Sequence[str], None] = '4c0d8feddc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'publication_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'publication_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
