"""named-area-zh

Revision ID: f253a629304a
Revises: c377ab79cc5c
Create Date: 2025-09-02 18:52:15.088502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f253a629304a'
down_revision: Union[str, Sequence[str], None] = 'c377ab79cc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('named_area', sa.Column('name_zh', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('named_area', 'name_zh')
    # ### end Alembic commands ###
